// Peripheral: PWR_Periph  Power Control.
// Instances:
//  PWR  mmap.PWR_BASE
// Registers:
//  0x00 32  CR  Power control register.
//  0x04 32  CSR Power control/status register.
// Import:
//  stm32/o/f303xe/mmap
package pwr

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	LPDS     CR = 0x01 << 0 //+ Low-power Deepsleep.
	PDDS     CR = 0x01 << 1 //+ Power Down Deepsleep.
	CWUF     CR = 0x01 << 2 //+ Clear Wakeup Flag.
	CSBF     CR = 0x01 << 3 //+ Clear Standby Flag.
	PVDE     CR = 0x01 << 4 //+ Power Voltage Detector Enable.
	PLS      CR = 0x07 << 5 //+ PLS[2:0] bits (PVD Level Selection).
	PLS_LEV0 CR = 0x00 << 5 //  PVD level 0.
	PLS_LEV1 CR = 0x01 << 5 //  PVD level 1.
	PLS_LEV2 CR = 0x02 << 5 //  PVD level 2.
	PLS_LEV3 CR = 0x03 << 5 //  PVD level 3.
	PLS_LEV4 CR = 0x04 << 5 //  PVD level 4.
	PLS_LEV5 CR = 0x05 << 5 //  PVD level 5.
	PLS_LEV6 CR = 0x06 << 5 //  PVD level 6.
	PLS_LEV7 CR = 0x07 << 5 //  PVD level 7.
	DBP      CR = 0x01 << 8 //+ Disable Backup Domain write protection.
)

const (
	LPDSn = 0
	PDDSn = 1
	CWUFn = 2
	CSBFn = 3
	PVDEn = 4
	PLSn  = 5
	DBPn  = 8
)

const (
	WUF         CSR = 0x01 << 0  //+ Wakeup Flag.
	SBF         CSR = 0x01 << 1  //+ Standby Flag.
	PVDO        CSR = 0x01 << 2  //+ PVD Output.
	VREFINTRDYF CSR = 0x01 << 3  //+ Internal voltage reference (VREFINT) ready flag.
	EWUP1       CSR = 0x01 << 8  //+ Enable WKUP pin 1.
	EWUP2       CSR = 0x01 << 9  //+ Enable WKUP pin 2.
	EWUP3       CSR = 0x01 << 10 //+ Enable WKUP pin 3.
)

const (
	WUFn         = 0
	SBFn         = 1
	PVDOn        = 2
	VREFINTRDYFn = 3
	EWUP1n       = 8
	EWUP2n       = 9
	EWUP3n       = 10
)
