// +build l476xx

// Peripheral: SAI_Periph  Serial Audio Interface.
// Instances:
//  SAI1  mmap.SAI1_BASE
//  SAI2  mmap.SAI2_BASE
// Registers:
//  0x00 32  GCR Global configuration register.
// Import:
//  stm32/o/l476xx/mmap
package sai

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	SYNCIN  GCR = 0x03 << 0 //+ SYNCIN[1:0] bits (Synchronization Inputs).
	SYNCOUT GCR = 0x03 << 4 //+ SYNCOUT[1:0] bits (Synchronization Outputs).
)

const (
	SYNCINn  = 0
	SYNCOUTn = 4
)
