// +build l476xx

// Peripheral: FIREWALL_Periph  Firewall.
// Instances:
//  FIREWALL  mmap.FIREWALL_BASE
// Registers:
//  0x00 32  CSSA   Code Segment Start Address register.
//  0x04 32  CSL    Code Segment Length register.
//  0x08 32  NVDSSA NON volatile data Segment Start Address register.
//  0x0C 32  NVDSL  NON volatile data Segment Length register.
//  0x10 32  VDSSA  Volatile data Segment Start Address register.
//  0x14 32  VDSL   Volatile data Segment Length register.
//  0x20 32  CR     Configuration  register.
// Import:
//  stm32/o/l476xx/mmap
package firewall

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.
