// Peripheral: CRC_Periph  CRC calculation unit.
// Instances:
//  CRC  mmap.CRC_BASE
// Registers:
//  0x00 32  DR   Data register.
//  0x04  8  IDR  Independent data register.
//  0x08 32  CR   Control register.
//  0x10 32  INIT Initial CRC value register.
//  0x14 32  POL  Polynomial register.
// Import:
//  stm32/o/f303xe/mmap
package crc

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	RESET     CR_Bits = 0x01 << 0 //+ RESET the CRC computation unit bit.
	POLSIZE   CR_Bits = 0x03 << 3 //+ Polynomial size bits.
	POLSIZE_0 CR_Bits = 0x01 << 3 //  Polynomial size bit 0.
	POLSIZE_1 CR_Bits = 0x02 << 3 //  Polynomial size bit 1.
	REV_IN    CR_Bits = 0x03 << 5 //+ REV_IN Reverse Input Data bits.
	REV_IN_0  CR_Bits = 0x01 << 5 //  Bit 0.
	REV_IN_1  CR_Bits = 0x02 << 5 //  Bit 1.
	REV_OUT   CR_Bits = 0x01 << 7 //+ REV_OUT Reverse Output Data bits.
)

const (
	RESETn   = 0
	POLSIZEn = 3
	REV_INn  = 5
	REV_OUTn = 7
)
