// +build f303xe

// Peripheral: HRTIM_Common_Periph  High resolution Timer (HRTIM).
// Instances:
//  HRTIM1_COMMON  mmap.HRTIM1_COMMON_BASE
// Registers:
//  0x00 32  CR1      HRTIM control register1.
//  0x04 32  CR2      HRTIM control register2.
//  0x08 32  ISR      HRTIM interrupt status register.
//  0x0C 32  ICR      HRTIM interrupt clear register.
//  0x10 32  IER      HRTIM interrupt enable register.
//  0x14 32  OENR     HRTIM Output enable register.
//  0x18 32  DISR     HRTIM Output disable register.
//  0x1C 32  ODSR     HRTIM Output disable status register.
//  0x20 32  BMCR     HRTIM Burst mode control register.
//  0x24 32  BMTRGR   HRTIM Busrt mode trigger register.
//  0x28 32  BMCMPR   HRTIM Burst mode compare register.
//  0x2C 32  BMPER    HRTIM Burst mode period register.
//  0x30 32  EECR1    HRTIM Timer external event control register1.
//  0x34 32  EECR2    HRTIM Timer external event control register2.
//  0x38 32  EECR3    HRTIM Timer external event control register3.
//  0x3C 32  ADC1R    HRTIM ADC Trigger 1 register.
//  0x40 32  ADC2R    HRTIM ADC Trigger 2 register.
//  0x44 32  ADC3R    HRTIM ADC Trigger 3 register.
//  0x48 32  ADC4R    HRTIM ADC Trigger 4 register.
//  0x4C 32  DLLCR    HRTIM DLL control register.
//  0x50 32  FLTINxR1 HRTIM Fault input register1.
//  0x54 32  FLTINxR2 HRTIM Fault input register2.
//  0x58 32  BDMUPDR  HRTIM Burst DMA Master Timer update register.
//  0x5C 32  BDTAUPR  HRTIM Burst DMA Timerx update register.
//  0x60 32  BDTBUPR  HRTIM Burst DMA Timerx update register.
//  0x64 32  BDTCUPR  HRTIM Burst DMA Timerx update register.
//  0x68 32  BDTDUPR  HRTIM Burst DMA Timerx update register.
//  0x6C 32  BDTEUPR  HRTIM Burst DMA Timerx update register.
//  0x70 32  BDMADR   HRTIM Burst DMA Master Data register.
// Import:
//  stm32/o/f303xe/mmap
package hrtim

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.

const (
	MUDIS      CR1_Bits = 0x01 << 0  //+ Master update disable.
	TAUDIS     CR1_Bits = 0x01 << 1  //+ Timer A update disable.
	TBUDIS     CR1_Bits = 0x01 << 2  //+ Timer B update disable.
	TCUDIS     CR1_Bits = 0x01 << 3  //+ Timer C update disable.
	TDUDIS     CR1_Bits = 0x01 << 4  //+ Timer D update disable.
	TEUDIS     CR1_Bits = 0x01 << 5  //+ Timer E update disable.
	ADC1USRC   CR1_Bits = 0x07 << 16 //+ ADC Trigger 1 update source.
	ADC1USRC_0 CR1_Bits = 0x01 << 16 //  ADC Trigger 1 update source bit 0.
	ADC1USRC_1 CR1_Bits = 0x02 << 16 //  ADC Trigger 1 update source bit 1.
	ADC1USRC_2 CR1_Bits = 0x04 << 16 //  ADC Trigger 1 update source bit 2.
	ADC2USRC   CR1_Bits = 0x07 << 19 //+ ADC Trigger 2 update source.
	ADC2USRC_0 CR1_Bits = 0x01 << 19 //  ADC Trigger 2 update source bit 0.
	ADC2USRC_1 CR1_Bits = 0x02 << 19 //  ADC Trigger 2 update source bit 1.
	ADC2USRC_2 CR1_Bits = 0x04 << 19 //  ADC Trigger 2 update source bit 2.
	ADC3USRC   CR1_Bits = 0x07 << 22 //+ ADC Trigger 3 update source.
	ADC3USRC_0 CR1_Bits = 0x01 << 22 //  ADC Trigger 3 update source bit 0.
	ADC3USRC_1 CR1_Bits = 0x02 << 22 //  ADC Trigger 3 update source bit 1.
	ADC3USRC_2 CR1_Bits = 0x04 << 22 //  ADC Trigger 3 update source bit 2.
	ADC4USRC   CR1_Bits = 0x07 << 25 //+ ADC Trigger 4 update source.
	ADC4USRC_0 CR1_Bits = 0x01 << 25 //  ADC Trigger 4 update source bit 0.
	ADC4USRC_1 CR1_Bits = 0x02 << 25 //  ADC Trigger 4 update source bit 1.
	ADC4USRC_2 CR1_Bits = 0x02 << 22 //  ADC Trigger 4 update source bit 2.
)

const (
	MUDISn    = 0
	TAUDISn   = 1
	TBUDISn   = 2
	TCUDISn   = 3
	TDUDISn   = 4
	TEUDISn   = 5
	ADC1USRCn = 16
	ADC2USRCn = 19
	ADC3USRCn = 22
	ADC4USRCn = 25
)

const (
	MSWU  CR2_Bits = 0x01 << 0  //+ Master software update.
	TASWU CR2_Bits = 0x01 << 1  //+ Timer A software update.
	TBSWU CR2_Bits = 0x01 << 2  //+ Timer B software update.
	TCSWU CR2_Bits = 0x01 << 3  //+ Timer C software update.
	TDSWU CR2_Bits = 0x01 << 4  //+ Timer D software update.
	TESWU CR2_Bits = 0x01 << 5  //+ Timer E software update.
	MRST  CR2_Bits = 0x01 << 8  //+ Master count software reset.
	TARST CR2_Bits = 0x01 << 9  //+ Timer A count software reset.
	TBRST CR2_Bits = 0x01 << 10 //+ Timer B count software reset.
	TCRST CR2_Bits = 0x01 << 11 //+ Timer C count software reset.
	TDRST CR2_Bits = 0x01 << 12 //+ Timer D count software reset.
	TERST CR2_Bits = 0x01 << 13 //+ Timer E count software reset.
)

const (
	MSWUn  = 0
	TASWUn = 1
	TBSWUn = 2
	TCSWUn = 3
	TDSWUn = 4
	TESWUn = 5
	MRSTn  = 8
	TARSTn = 9
	TBRSTn = 10
	TCRSTn = 11
	TDRSTn = 12
	TERSTn = 13
)

const (
	FLT1   ISR_Bits = 0x01 << 0  //+ Fault 1 interrupt flag.
	FLT2   ISR_Bits = 0x01 << 1  //+ Fault 2 interrupt flag.
	FLT3   ISR_Bits = 0x01 << 2  //+ Fault 3 interrupt flag.
	FLT4   ISR_Bits = 0x01 << 3  //+ Fault 4 interrupt flag.
	FLT5   ISR_Bits = 0x01 << 4  //+ Fault 5 interrupt flag.
	SYSFLT ISR_Bits = 0x01 << 5  //+ System Fault interrupt flag.
	DLLRDY ISR_Bits = 0x01 << 16 //+ DLL ready interrupt flag.
	BMPER  ISR_Bits = 0x01 << 17 //+ Burst mode period interrupt flag.
)

const (
	FLT1n   = 0
	FLT2n   = 1
	FLT3n   = 2
	FLT4n   = 3
	FLT5n   = 4
	SYSFLTn = 5
	DLLRDYn = 16
	BMPERn  = 17
)

const (
	FLT1C   ICR_Bits = 0x01 << 0  //+ Fault 1 interrupt flag clear.
	FLT2C   ICR_Bits = 0x01 << 1  //+ Fault 2 interrupt flag clear.
	FLT3C   ICR_Bits = 0x01 << 2  //+ Fault 3 interrupt flag clear.
	FLT4C   ICR_Bits = 0x01 << 3  //+ Fault 4 interrupt flag clear.
	FLT5C   ICR_Bits = 0x01 << 4  //+ Fault 5 interrupt flag clear.
	SYSFLTC ICR_Bits = 0x01 << 5  //+ System Fault interrupt flag clear.
	DLLRDYC ICR_Bits = 0x01 << 16 //+ DLL ready interrupt flag clear.
	BMPERC  ICR_Bits = 0x01 << 17 //+ Burst mode period interrupt flag clear.
)

const (
	FLT1Cn   = 0
	FLT2Cn   = 1
	FLT3Cn   = 2
	FLT4Cn   = 3
	FLT5Cn   = 4
	SYSFLTCn = 5
	DLLRDYCn = 16
	BMPERCn  = 17
)

const (
	FLT1   IER_Bits = 0x01 << 0  //+ Fault 1 interrupt enable.
	FLT2   IER_Bits = 0x01 << 1  //+ Fault 2 interrupt enable.
	FLT3   IER_Bits = 0x01 << 2  //+ Fault 3 interrupt enable.
	FLT4   IER_Bits = 0x01 << 3  //+ Fault 4 interrupt enable.
	FLT5   IER_Bits = 0x01 << 4  //+ Fault 5 interrupt enable.
	SYSFLT IER_Bits = 0x01 << 5  //+ System Fault interrupt enable.
	DLLRDY IER_Bits = 0x01 << 16 //+ DLL ready interrupt enable.
	BMPER  IER_Bits = 0x01 << 17 //+ Burst mode period interrupt enable.
)

const (
	FLT1n   = 0
	FLT2n   = 1
	FLT3n   = 2
	FLT4n   = 3
	FLT5n   = 4
	SYSFLTn = 5
	DLLRDYn = 16
	BMPERn  = 17
)

const (
	TA1OEN OENR_Bits = 0x01 << 0 //+ Timer A Output 1 enable.
	TA2OEN OENR_Bits = 0x01 << 1 //+ Timer A Output 2 enable.
	TB1OEN OENR_Bits = 0x01 << 2 //+ Timer B Output 1 enable.
	TB2OEN OENR_Bits = 0x01 << 3 //+ Timer B Output 2 enable.
	TC1OEN OENR_Bits = 0x01 << 4 //+ Timer C Output 1 enable.
	TC2OEN OENR_Bits = 0x01 << 5 //+ Timer C Output 2 enable.
	TD1OEN OENR_Bits = 0x01 << 6 //+ Timer D Output 1 enable.
	TD2OEN OENR_Bits = 0x01 << 7 //+ Timer D Output 2 enable.
	TE1OEN OENR_Bits = 0x01 << 8 //+ Timer E Output 1 enable.
	TE2OEN OENR_Bits = 0x01 << 9 //+ Timer E Output 2 enable.
)

const (
	TA1OENn = 0
	TA2OENn = 1
	TB1OENn = 2
	TB2OENn = 3
	TC1OENn = 4
	TC2OENn = 5
	TD1OENn = 6
	TD2OENn = 7
	TE1OENn = 8
	TE2OENn = 9
)

const (
	TA1ODS ODSR_Bits = 0x01 << 0 //+ Timer A Output 1 disable status.
	TA2ODS ODSR_Bits = 0x01 << 1 //+ Timer A Output 2 disable status.
	TB1ODS ODSR_Bits = 0x01 << 2 //+ Timer B Output 1 disable status.
	TB2ODS ODSR_Bits = 0x01 << 3 //+ Timer B Output 2 disable status.
	TC1ODS ODSR_Bits = 0x01 << 4 //+ Timer C Output 1 disable status.
	TC2ODS ODSR_Bits = 0x01 << 5 //+ Timer C Output 2 disable status.
	TD1ODS ODSR_Bits = 0x01 << 6 //+ Timer D Output 1 disable status.
	TD2ODS ODSR_Bits = 0x01 << 7 //+ Timer D Output 2 disable status.
	TE1ODS ODSR_Bits = 0x01 << 8 //+ Timer E Output 1 disable status.
	TE2ODS ODSR_Bits = 0x01 << 9 //+ Timer E Output 2 disable status.
)

const (
	TA1ODSn = 0
	TA2ODSn = 1
	TB1ODSn = 2
	TB2ODSn = 3
	TC1ODSn = 4
	TC2ODSn = 5
	TD1ODSn = 6
	TD2ODSn = 7
	TE1ODSn = 8
	TE2ODSn = 9
)

const (
	BME     BMCR_Bits = 0x01 << 0  //+ Burst mode enable.
	BMOM    BMCR_Bits = 0x01 << 1  //+ Burst mode operating mode.
	BMCLK   BMCR_Bits = 0x0F << 2  //+ Burst mode clock source.
	BMCLK_0 BMCR_Bits = 0x01 << 2  //  Burst mode clock source bit 0.
	BMCLK_1 BMCR_Bits = 0x02 << 2  //  Burst mode clock source bit 1.
	BMCLK_2 BMCR_Bits = 0x04 << 2  //  Burst mode clock source bit 2.
	BMCLK_3 BMCR_Bits = 0x08 << 2  //  Burst mode clock source bit 3.
	BMPSC   BMCR_Bits = 0x0F << 6  //+ Burst mode prescaler.
	BMPSC_0 BMCR_Bits = 0x01 << 6  //  Burst mode prescaler bit 0.
	BMPSC_1 BMCR_Bits = 0x02 << 6  //  Burst mode prescaler bit 1.
	BMPSC_2 BMCR_Bits = 0x04 << 6  //  Burst mode prescaler bit 2.
	BMPSC_3 BMCR_Bits = 0x08 << 6  //  Burst mode prescaler bit 3.
	BMPREN  BMCR_Bits = 0x01 << 10 //+ Burst mode Preload bit.
	MTBM    BMCR_Bits = 0x01 << 16 //+ Master Timer Burst mode.
	TABM    BMCR_Bits = 0x01 << 17 //+ Timer A Burst mode.
	TBBM    BMCR_Bits = 0x01 << 18 //+ Timer B Burst mode.
	TCBM    BMCR_Bits = 0x01 << 19 //+ Timer C Burst mode.
	TDBM    BMCR_Bits = 0x01 << 20 //+ Timer D Burst mode.
	TEBM    BMCR_Bits = 0x01 << 21 //+ Timer E Burst mode.
	BMSTAT  BMCR_Bits = 0x01 << 31 //+ Burst mode status.
)

const (
	BMEn    = 0
	BMOMn   = 1
	BMCLKn  = 2
	BMPSCn  = 6
	BMPRENn = 10
	MTBMn   = 16
	TABMn   = 17
	TBBMn   = 18
	TCBMn   = 19
	TDBMn   = 20
	TEBMn   = 21
	BMSTATn = 31
)

const (
	SW      BMTRGR_Bits = 0x01 << 0  //+ Software start.
	MSTRST  BMTRGR_Bits = 0x01 << 1  //+ Master reset.
	MSTREP  BMTRGR_Bits = 0x01 << 2  //+ Master repetition.
	MSTCMP1 BMTRGR_Bits = 0x01 << 3  //+ Master compare 1.
	MSTCMP2 BMTRGR_Bits = 0x01 << 4  //+ Master compare 2.
	MSTCMP3 BMTRGR_Bits = 0x01 << 5  //+ Master compare 3.
	MSTCMP4 BMTRGR_Bits = 0x01 << 6  //+ Master compare 4.
	TARST   BMTRGR_Bits = 0x01 << 7  //+ Timer A reset.
	TAREP   BMTRGR_Bits = 0x01 << 8  //+ Timer A repetition.
	TACMP1  BMTRGR_Bits = 0x01 << 9  //+ Timer A compare 1.
	TACMP2  BMTRGR_Bits = 0x01 << 10 //+ Timer A compare 2.
	TBRST   BMTRGR_Bits = 0x01 << 11 //+ Timer B reset.
	TBREP   BMTRGR_Bits = 0x01 << 12 //+ Timer B repetition.
	TBCMP1  BMTRGR_Bits = 0x01 << 13 //+ Timer B compare 1.
	TBCMP2  BMTRGR_Bits = 0x01 << 14 //+ Timer B compare 2.
	TCRST   BMTRGR_Bits = 0x01 << 15 //+ Timer C reset.
	TCREP   BMTRGR_Bits = 0x01 << 16 //+ Timer C repetition.
	TCCMP1  BMTRGR_Bits = 0x01 << 17 //+ Timer C compare 1.
	TCCMP2  BMTRGR_Bits = 0x01 << 18 //+ Timer C compare 2.
	TDRST   BMTRGR_Bits = 0x01 << 19 //+ Timer D reset.
	TDREP   BMTRGR_Bits = 0x01 << 20 //+ Timer D repetition.
	TDCMP1  BMTRGR_Bits = 0x01 << 21 //+ Timer D compare 1.
	TDCMP2  BMTRGR_Bits = 0x01 << 22 //+ Timer D compare 2.
	TERST   BMTRGR_Bits = 0x01 << 23 //+ Timer E reset.
	TEREP   BMTRGR_Bits = 0x01 << 24 //+ Timer E repetition.
	TECMP1  BMTRGR_Bits = 0x01 << 25 //+ Timer E compare 1.
	TECMP2  BMTRGR_Bits = 0x01 << 26 //+ Timer E compare 2.
	TAEEV7  BMTRGR_Bits = 0x01 << 27 //+ Timer A period following External Event7.
	TDEEV8  BMTRGR_Bits = 0x01 << 28 //+ Timer D period following External Event8.
	EEV7    BMTRGR_Bits = 0x01 << 29 //+ External Event 7.
	EEV8    BMTRGR_Bits = 0x01 << 30 //+ External Event 8.
	OCHPEV  BMTRGR_Bits = 0x01 << 31 //+ on-chip Event.
)

const (
	SWn      = 0
	MSTRSTn  = 1
	MSTREPn  = 2
	MSTCMP1n = 3
	MSTCMP2n = 4
	MSTCMP3n = 5
	MSTCMP4n = 6
	TARSTn   = 7
	TAREPn   = 8
	TACMP1n  = 9
	TACMP2n  = 10
	TBRSTn   = 11
	TBREPn   = 12
	TBCMP1n  = 13
	TBCMP2n  = 14
	TCRSTn   = 15
	TCREPn   = 16
	TCCMP1n  = 17
	TCCMP2n  = 18
	TDRSTn   = 19
	TDREPn   = 20
	TDCMP1n  = 21
	TDCMP2n  = 22
	TERSTn   = 23
	TEREPn   = 24
	TECMP1n  = 25
	TECMP2n  = 26
	TAEEV7n  = 27
	TDEEV8n  = 28
	EEV7n    = 29
	EEV8n    = 30
	OCHPEVn  = 31
)

const (
	EE1SRC   EECR1_Bits = 0x03 << 0  //+ External event 1 source.
	EE1SRC_0 EECR1_Bits = 0x01 << 0  //  External event 1 source bit 0.
	EE1SRC_1 EECR1_Bits = 0x02 << 0  //  External event 1 source bit 1.
	EE1POL   EECR1_Bits = 0x01 << 2  //+ External event 1 Polarity.
	EE1SNS   EECR1_Bits = 0x03 << 3  //+ External event 1 sensitivity.
	EE1SNS_0 EECR1_Bits = 0x01 << 3  //  External event 1 sensitivity bit 0.
	EE1SNS_1 EECR1_Bits = 0x02 << 3  //  External event 1 sensitivity bit 1.
	EE1FAST  EECR1_Bits = 0x01 << 5  //+ External event 1 Fast mode.
	EE2SRC   EECR1_Bits = 0x03 << 6  //+ External event 2 source.
	EE2SRC_0 EECR1_Bits = 0x01 << 6  //  External event 2 source bit 0.
	EE2SRC_1 EECR1_Bits = 0x02 << 6  //  External event 2 source bit 1.
	EE2POL   EECR1_Bits = 0x01 << 8  //+ External event 2 Polarity.
	EE2SNS   EECR1_Bits = 0x03 << 9  //+ External event 2 sensitivity.
	EE2SNS_0 EECR1_Bits = 0x01 << 9  //  External event 2 sensitivity bit 0.
	EE2SNS_1 EECR1_Bits = 0x02 << 9  //  External event 2 sensitivity bit 1.
	EE2FAST  EECR1_Bits = 0x01 << 11 //+ External event 2 Fast mode.
	EE3SRC   EECR1_Bits = 0x03 << 12 //+ External event 3 source.
	EE3SRC_0 EECR1_Bits = 0x01 << 12 //  External event 3 source bit 0.
	EE3SRC_1 EECR1_Bits = 0x02 << 12 //  External event 3 source bit 1.
	EE3POL   EECR1_Bits = 0x01 << 14 //+ External event 3 Polarity.
	EE3SNS   EECR1_Bits = 0x03 << 15 //+ External event 3 sensitivity.
	EE3SNS_0 EECR1_Bits = 0x01 << 15 //  External event 3 sensitivity bit 0.
	EE3SNS_1 EECR1_Bits = 0x02 << 15 //  External event 3 sensitivity bit 1.
	EE3FAST  EECR1_Bits = 0x01 << 17 //+ External event 3 Fast mode.
	EE4SRC   EECR1_Bits = 0x03 << 18 //+ External event 4 source.
	EE4SRC_0 EECR1_Bits = 0x01 << 18 //  External event 4 source bit 0.
	EE4SRC_1 EECR1_Bits = 0x02 << 18 //  External event 4 source bit 1.
	EE4POL   EECR1_Bits = 0x01 << 20 //+ External event 4 Polarity.
	EE4SNS   EECR1_Bits = 0x03 << 21 //+ External event 4 sensitivity.
	EE4SNS_0 EECR1_Bits = 0x01 << 21 //  External event 4 sensitivity bit 0.
	EE4SNS_1 EECR1_Bits = 0x02 << 21 //  External event 4 sensitivity bit 1.
	EE4FAST  EECR1_Bits = 0x01 << 23 //+ External event 4 Fast mode.
	EE5SRC   EECR1_Bits = 0x03 << 24 //+ External event 5 source.
	EE5SRC_0 EECR1_Bits = 0x01 << 24 //  External event 5 source bit 0.
	EE5SRC_1 EECR1_Bits = 0x02 << 24 //  External event 5 source bit 1.
	EE5POL   EECR1_Bits = 0x01 << 26 //+ External event 5 Polarity.
	EE5SNS   EECR1_Bits = 0x03 << 27 //+ External event 5 sensitivity.
	EE5SNS_0 EECR1_Bits = 0x01 << 27 //  External event 5 sensitivity bit 0.
	EE5SNS_1 EECR1_Bits = 0x02 << 27 //  External event 5 sensitivity bit 1.
	EE5FAST  EECR1_Bits = 0x01 << 29 //+ External event 5 Fast mode.
)

const (
	EE1SRCn  = 0
	EE1POLn  = 2
	EE1SNSn  = 3
	EE1FASTn = 5
	EE2SRCn  = 6
	EE2POLn  = 8
	EE2SNSn  = 9
	EE2FASTn = 11
	EE3SRCn  = 12
	EE3POLn  = 14
	EE3SNSn  = 15
	EE3FASTn = 17
	EE4SRCn  = 18
	EE4POLn  = 20
	EE4SNSn  = 21
	EE4FASTn = 23
	EE5SRCn  = 24
	EE5POLn  = 26
	EE5SNSn  = 27
	EE5FASTn = 29
)

const (
	EE6SRC    EECR2_Bits = 0x03 << 0  //+ External event 6 source.
	EE6SRC_0  EECR2_Bits = 0x01 << 0  //  External event 6 source bit 0.
	EE6SRC_1  EECR2_Bits = 0x02 << 0  //  External event 6 source bit 1.
	EE6POL    EECR2_Bits = 0x01 << 2  //+ External event 6 Polarity.
	EE6SNS    EECR2_Bits = 0x03 << 3  //+ External event 6 sensitivity.
	EE6SNS_0  EECR2_Bits = 0x01 << 3  //  External event 6 sensitivity bit 0.
	EE6SNS_1  EECR2_Bits = 0x02 << 3  //  External event 6 sensitivity bit 1.
	EE7SRC    EECR2_Bits = 0x03 << 6  //+ External event 7 source.
	EE7SRC_0  EECR2_Bits = 0x01 << 6  //  External event 7 source bit 0.
	EE7SRC_1  EECR2_Bits = 0x02 << 6  //  External event 7 source bit 1.
	EE7POL    EECR2_Bits = 0x01 << 8  //+ External event 7 Polarity.
	EE7SNS    EECR2_Bits = 0x03 << 9  //+ External event 7 sensitivity.
	EE7SNS_0  EECR2_Bits = 0x01 << 9  //  External event 7 sensitivity bit 0.
	EE7SNS_1  EECR2_Bits = 0x02 << 9  //  External event 7 sensitivity bit 1.
	EE8SRC    EECR2_Bits = 0x03 << 12 //+ External event 8 source.
	EE8SRC_0  EECR2_Bits = 0x01 << 12 //  External event 8 source bit 0.
	EE8SRC_1  EECR2_Bits = 0x02 << 12 //  External event 8 source bit 1.
	EE8POL    EECR2_Bits = 0x01 << 14 //+ External event 8 Polarity.
	EE8SNS    EECR2_Bits = 0x03 << 15 //+ External event 8 sensitivity.
	EE8SNS_0  EECR2_Bits = 0x01 << 15 //  External event 8 sensitivity bit 0.
	EE8SNS_1  EECR2_Bits = 0x02 << 15 //  External event 8 sensitivity bit 1.
	EE9SRC    EECR2_Bits = 0x03 << 18 //+ External event 9 source.
	EE9SRC_0  EECR2_Bits = 0x01 << 18 //  External event 9 source bit 0.
	EE9SRC_1  EECR2_Bits = 0x02 << 18 //  External event 9 source bit 1.
	EE9POL    EECR2_Bits = 0x01 << 20 //+ External event 9 Polarity.
	EE9SNS    EECR2_Bits = 0x03 << 21 //+ External event 9 sensitivity.
	EE9SNS_0  EECR2_Bits = 0x01 << 21 //  External event 9 sensitivity bit 0.
	EE9SNS_1  EECR2_Bits = 0x02 << 21 //  External event 9 sensitivity bit 1.
	EE10SRC   EECR2_Bits = 0x03 << 24 //+ External event 10 source.
	EE10SRC_0 EECR2_Bits = 0x01 << 24 //  External event 10 source bit 0.
	EE10SRC_1 EECR2_Bits = 0x02 << 24 //  External event 10 source bit 1.
	EE10POL   EECR2_Bits = 0x01 << 26 //+ External event 10 Polarity.
	EE10SNS   EECR2_Bits = 0x03 << 27 //+ External event 10 sensitivity.
	EE10SNS_0 EECR2_Bits = 0x01 << 27 //  External event 10 sensitivity bit 0.
	EE10SNS_1 EECR2_Bits = 0x02 << 27 //  External event 10 sensitivity bit 1.
)

const (
	EE6SRCn  = 0
	EE6POLn  = 2
	EE6SNSn  = 3
	EE7SRCn  = 6
	EE7POLn  = 8
	EE7SNSn  = 9
	EE8SRCn  = 12
	EE8POLn  = 14
	EE8SNSn  = 15
	EE9SRCn  = 18
	EE9POLn  = 20
	EE9SNSn  = 21
	EE10SRCn = 24
	EE10POLn = 26
	EE10SNSn = 27
)

const (
	EE6F    EECR3_Bits = 0x0F << 0  //+ External event 6 filter.
	EE6F_0  EECR3_Bits = 0x01 << 0  //  External event 6 filter bit 0.
	EE6F_1  EECR3_Bits = 0x02 << 0  //  External event 6 filter bit 1.
	EE6F_2  EECR3_Bits = 0x04 << 0  //  External event 6 filter bit 2.
	EE6F_3  EECR3_Bits = 0x08 << 0  //  External event 6 filter bit 3.
	EE7F    EECR3_Bits = 0x0F << 6  //+ External event 7 filter.
	EE7F_0  EECR3_Bits = 0x01 << 6  //  External event 7 filter bit 0.
	EE7F_1  EECR3_Bits = 0x02 << 6  //  External event 7 filter bit 1.
	EE7F_2  EECR3_Bits = 0x04 << 6  //  External event 7 filter bit 2.
	EE7F_3  EECR3_Bits = 0x08 << 6  //  External event 7 filter bit 3.
	EE8F    EECR3_Bits = 0x0F << 12 //+ External event 8 filter.
	EE8F_0  EECR3_Bits = 0x01 << 12 //  External event 8 filter bit 0.
	EE8F_1  EECR3_Bits = 0x02 << 12 //  External event 8 filter bit 1.
	EE8F_2  EECR3_Bits = 0x04 << 12 //  External event 8 filter bit 2.
	EE8F_3  EECR3_Bits = 0x08 << 12 //  External event 8 filter bit 3.
	EE9F    EECR3_Bits = 0x0F << 18 //+ External event 9 filter.
	EE9F_0  EECR3_Bits = 0x01 << 18 //  External event 9 filter bit 0.
	EE9F_1  EECR3_Bits = 0x02 << 18 //  External event 9 filter bit 1.
	EE9F_2  EECR3_Bits = 0x04 << 18 //  External event 9 filter bit 2.
	EE9F_3  EECR3_Bits = 0x08 << 18 //  External event 9 filter bit 3.
	EE10F   EECR3_Bits = 0x0F << 24 //+ External event 10 filter.
	EE10F_0 EECR3_Bits = 0x01 << 24 //  External event 10 filter bit 0.
	EE10F_1 EECR3_Bits = 0x02 << 24 //  External event 10 filter bit 1.
	EE10F_2 EECR3_Bits = 0x04 << 24 //  External event 10 filter bit 2.
	EE10F_3 EECR3_Bits = 0x08 << 24 //  External event 10 filter bit 3.
	EEVSD   EECR3_Bits = 0x03 << 30 //+ External event sampling clock division.
	EEVSD_0 EECR3_Bits = 0x01 << 30 //  External event sampling clock division bit 0.
	EEVSD_1 EECR3_Bits = 0x02 << 30 //  External event sampling clock division bit 1.
)

const (
	EE6Fn  = 0
	EE7Fn  = 6
	EE8Fn  = 12
	EE9Fn  = 18
	EE10Fn = 24
	EEVSDn = 30
)

const (
	AD1MC1   ADC1R_Bits = 0x01 << 0  //+ ADC Trigger 1 on master compare 1.
	AD1MC2   ADC1R_Bits = 0x01 << 1  //+ ADC Trigger 1 on master compare 2.
	AD1MC3   ADC1R_Bits = 0x01 << 2  //+ ADC Trigger 1 on master compare 3.
	AD1MC4   ADC1R_Bits = 0x01 << 3  //+ ADC Trigger 1 on master compare 4.
	AD1MPER  ADC1R_Bits = 0x01 << 4  //+ ADC Trigger 1 on master period.
	AD1EEV1  ADC1R_Bits = 0x01 << 5  //+ ADC Trigger 1 on external event 1.
	AD1EEV2  ADC1R_Bits = 0x01 << 6  //+ ADC Trigger 1 on external event 2.
	AD1EEV3  ADC1R_Bits = 0x01 << 7  //+ ADC Trigger 1 on external event 3.
	AD1EEV4  ADC1R_Bits = 0x01 << 8  //+ ADC Trigger 1 on external event 4.
	AD1EEV5  ADC1R_Bits = 0x01 << 9  //+ ADC Trigger 1 on external event 5.
	AD1TAC2  ADC1R_Bits = 0x01 << 10 //+ ADC Trigger 1 on Timer A compare 2.
	AD1TAC3  ADC1R_Bits = 0x01 << 11 //+ ADC Trigger 1 on Timer A compare 3.
	AD1TAC4  ADC1R_Bits = 0x01 << 12 //+ ADC Trigger 1 on Timer A compare 4.
	AD1TAPER ADC1R_Bits = 0x01 << 13 //+ ADC Trigger 1 on Timer A period.
	AD1TARST ADC1R_Bits = 0x01 << 14 //+ ADC Trigger 1 on Timer A reset.
	AD1TBC2  ADC1R_Bits = 0x01 << 15 //+ ADC Trigger 1 on Timer B compare 2.
	AD1TBC3  ADC1R_Bits = 0x01 << 16 //+ ADC Trigger 1 on Timer B compare 3.
	AD1TBC4  ADC1R_Bits = 0x01 << 17 //+ ADC Trigger 1 on Timer B compare 4.
	AD1TBPER ADC1R_Bits = 0x01 << 18 //+ ADC Trigger 1 on Timer B period.
	AD1TBRST ADC1R_Bits = 0x01 << 19 //+ ADC Trigger 1 on Timer B reset.
	AD1TCC2  ADC1R_Bits = 0x01 << 20 //+ ADC Trigger 1 on Timer C compare 2.
	AD1TCC3  ADC1R_Bits = 0x01 << 21 //+ ADC Trigger 1 on Timer C compare 3.
	AD1TCC4  ADC1R_Bits = 0x01 << 22 //+ ADC Trigger 1 on Timer C compare 4.
	AD1TCPER ADC1R_Bits = 0x01 << 23 //+ ADC Trigger 1 on Timer C period.
	AD1TDC2  ADC1R_Bits = 0x01 << 24 //+ ADC Trigger 1 on Timer D compare 2.
	AD1TDC3  ADC1R_Bits = 0x01 << 25 //+ ADC Trigger 1 on Timer D compare 3.
	AD1TDC4  ADC1R_Bits = 0x01 << 26 //+ ADC Trigger 1 on Timer D compare 4.
	AD1TDPER ADC1R_Bits = 0x01 << 27 //+ ADC Trigger 1 on Timer D period.
	AD1TEC2  ADC1R_Bits = 0x01 << 28 //+ ADC Trigger 1 on Timer E compare 2.
	AD1TEC3  ADC1R_Bits = 0x01 << 29 //+ ADC Trigger 1 on Timer E compare 3.
	AD1TEC4  ADC1R_Bits = 0x01 << 30 //+ ADC Trigger 1 on Timer E compare 4.
	AD1TEPER ADC1R_Bits = 0x01 << 31 //+ ADC Trigger 1 on Timer E period.
)

const (
	AD1MC1n   = 0
	AD1MC2n   = 1
	AD1MC3n   = 2
	AD1MC4n   = 3
	AD1MPERn  = 4
	AD1EEV1n  = 5
	AD1EEV2n  = 6
	AD1EEV3n  = 7
	AD1EEV4n  = 8
	AD1EEV5n  = 9
	AD1TAC2n  = 10
	AD1TAC3n  = 11
	AD1TAC4n  = 12
	AD1TAPERn = 13
	AD1TARSTn = 14
	AD1TBC2n  = 15
	AD1TBC3n  = 16
	AD1TBC4n  = 17
	AD1TBPERn = 18
	AD1TBRSTn = 19
	AD1TCC2n  = 20
	AD1TCC3n  = 21
	AD1TCC4n  = 22
	AD1TCPERn = 23
	AD1TDC2n  = 24
	AD1TDC3n  = 25
	AD1TDC4n  = 26
	AD1TDPERn = 27
	AD1TEC2n  = 28
	AD1TEC3n  = 29
	AD1TEC4n  = 30
	AD1TEPERn = 31
)

const (
	AD2MC1   ADC2R_Bits = 0x01 << 0  //+ ADC Trigger 2 on master compare 1.
	AD2MC2   ADC2R_Bits = 0x01 << 1  //+ ADC Trigger 2 on master compare 2.
	AD2MC3   ADC2R_Bits = 0x01 << 2  //+ ADC Trigger 2 on master compare 3.
	AD2MC4   ADC2R_Bits = 0x01 << 3  //+ ADC Trigger 2 on master compare 4.
	AD2MPER  ADC2R_Bits = 0x01 << 4  //+ ADC Trigger 2 on master period.
	AD2EEV6  ADC2R_Bits = 0x01 << 5  //+ ADC Trigger 2 on external event 6.
	AD2EEV7  ADC2R_Bits = 0x01 << 6  //+ ADC Trigger 2 on external event 7.
	AD2EEV8  ADC2R_Bits = 0x01 << 7  //+ ADC Trigger 2 on external event 8.
	AD2EEV9  ADC2R_Bits = 0x01 << 8  //+ ADC Trigger 2 on external event 9.
	AD2EEV10 ADC2R_Bits = 0x01 << 9  //+ ADC Trigger 2 on external event 10.
	AD2TAC2  ADC2R_Bits = 0x01 << 10 //+ ADC Trigger 2 on Timer A compare 2.
	AD2TAC3  ADC2R_Bits = 0x01 << 11 //+ ADC Trigger 2 on Timer A compare 3.
	AD2TAC4  ADC2R_Bits = 0x01 << 12 //+ ADC Trigger 2 on Timer A compare 4.
	AD2TAPER ADC2R_Bits = 0x01 << 13 //+ ADC Trigger 2 on Timer A period.
	AD2TBC2  ADC2R_Bits = 0x01 << 14 //+ ADC Trigger 2 on Timer B compare 2.
	AD2TBC3  ADC2R_Bits = 0x01 << 15 //+ ADC Trigger 2 on Timer B compare 3.
	AD2TBC4  ADC2R_Bits = 0x01 << 16 //+ ADC Trigger 2 on Timer B compare 4.
	AD2TBPER ADC2R_Bits = 0x01 << 17 //+ ADC Trigger 2 on Timer B period.
	AD2TCC2  ADC2R_Bits = 0x01 << 18 //+ ADC Trigger 2 on Timer C compare 2.
	AD2TCC3  ADC2R_Bits = 0x01 << 19 //+ ADC Trigger 2 on Timer C compare 3.
	AD2TCC4  ADC2R_Bits = 0x01 << 20 //+ ADC Trigger 2 on Timer C compare 4.
	AD2TCPER ADC2R_Bits = 0x01 << 21 //+ ADC Trigger 2 on Timer C period.
	AD2TCRST ADC2R_Bits = 0x01 << 22 //+ ADC Trigger 2 on Timer C reset.
	AD2TDC2  ADC2R_Bits = 0x01 << 23 //+ ADC Trigger 2 on Timer D compare 2.
	AD2TDC3  ADC2R_Bits = 0x01 << 24 //+ ADC Trigger 2 on Timer D compare 3.
	AD2TDC4  ADC2R_Bits = 0x01 << 25 //+ ADC Trigger 2 on Timer D compare 4.
	AD2TDPER ADC2R_Bits = 0x01 << 26 //+ ADC Trigger 2 on Timer D period.
	AD2TDRST ADC2R_Bits = 0x01 << 27 //+ ADC Trigger 2 on Timer D reset.
	AD2TEC2  ADC2R_Bits = 0x01 << 28 //+ ADC Trigger 2 on Timer E compare 2.
	AD2TEC3  ADC2R_Bits = 0x01 << 29 //+ ADC Trigger 2 on Timer E compare 3.
	AD2TEC4  ADC2R_Bits = 0x01 << 30 //+ ADC Trigger 2 on Timer E compare 4.
	AD2TERST ADC2R_Bits = 0x01 << 31 //+ ADC Trigger 2 on Timer E reset.
)

const (
	AD2MC1n   = 0
	AD2MC2n   = 1
	AD2MC3n   = 2
	AD2MC4n   = 3
	AD2MPERn  = 4
	AD2EEV6n  = 5
	AD2EEV7n  = 6
	AD2EEV8n  = 7
	AD2EEV9n  = 8
	AD2EEV10n = 9
	AD2TAC2n  = 10
	AD2TAC3n  = 11
	AD2TAC4n  = 12
	AD2TAPERn = 13
	AD2TBC2n  = 14
	AD2TBC3n  = 15
	AD2TBC4n  = 16
	AD2TBPERn = 17
	AD2TCC2n  = 18
	AD2TCC3n  = 19
	AD2TCC4n  = 20
	AD2TCPERn = 21
	AD2TCRSTn = 22
	AD2TDC2n  = 23
	AD2TDC3n  = 24
	AD2TDC4n  = 25
	AD2TDPERn = 26
	AD2TDRSTn = 27
	AD2TEC2n  = 28
	AD2TEC3n  = 29
	AD2TEC4n  = 30
	AD2TERSTn = 31
)

const (
	AD3MC1   ADC3R_Bits = 0x01 << 0  //+ ADC Trigger 3 on master compare 1.
	AD3MC2   ADC3R_Bits = 0x01 << 1  //+ ADC Trigger 3 on master compare 2.
	AD3MC3   ADC3R_Bits = 0x01 << 2  //+ ADC Trigger 3 on master compare 3.
	AD3MC4   ADC3R_Bits = 0x01 << 3  //+ ADC Trigger 3 on master compare 4.
	AD3MPER  ADC3R_Bits = 0x01 << 4  //+ ADC Trigger 3 on master period.
	AD3EEV1  ADC3R_Bits = 0x01 << 5  //+ ADC Trigger 3 on external event 1.
	AD3EEV2  ADC3R_Bits = 0x01 << 6  //+ ADC Trigger 3 on external event 2.
	AD3EEV3  ADC3R_Bits = 0x01 << 7  //+ ADC Trigger 3 on external event 3.
	AD3EEV4  ADC3R_Bits = 0x01 << 8  //+ ADC Trigger 3 on external event 4.
	AD3EEV5  ADC3R_Bits = 0x01 << 9  //+ ADC Trigger 3 on external event 5.
	AD3TAC2  ADC3R_Bits = 0x01 << 10 //+ ADC Trigger 3 on Timer A compare 2.
	AD3TAC3  ADC3R_Bits = 0x01 << 11 //+ ADC Trigger 3 on Timer A compare 3.
	AD3TAC4  ADC3R_Bits = 0x01 << 12 //+ ADC Trigger 3 on Timer A compare 4.
	AD3TAPER ADC3R_Bits = 0x01 << 13 //+ ADC Trigger 3 on Timer A period.
	AD3TARST ADC3R_Bits = 0x01 << 14 //+ ADC Trigger 3 on Timer A reset.
	AD3TBC2  ADC3R_Bits = 0x01 << 15 //+ ADC Trigger 3 on Timer B compare 2.
	AD3TBC3  ADC3R_Bits = 0x01 << 16 //+ ADC Trigger 3 on Timer B compare 3.
	AD3TBC4  ADC3R_Bits = 0x01 << 17 //+ ADC Trigger 3 on Timer B compare 4.
	AD3TBPER ADC3R_Bits = 0x01 << 18 //+ ADC Trigger 3 on Timer B period.
	AD3TBRST ADC3R_Bits = 0x01 << 19 //+ ADC Trigger 3 on Timer B reset.
	AD3TCC2  ADC3R_Bits = 0x01 << 20 //+ ADC Trigger 3 on Timer C compare 2.
	AD3TCC3  ADC3R_Bits = 0x01 << 21 //+ ADC Trigger 3 on Timer C compare 3.
	AD3TCC4  ADC3R_Bits = 0x01 << 22 //+ ADC Trigger 3 on Timer C compare 4.
	AD3TCPER ADC3R_Bits = 0x01 << 23 //+ ADC Trigger 3 on Timer C period.
	AD3TDC2  ADC3R_Bits = 0x01 << 24 //+ ADC Trigger 3 on Timer D compare 2.
	AD3TDC3  ADC3R_Bits = 0x01 << 25 //+ ADC Trigger 3 on Timer D compare 3.
	AD3TDC4  ADC3R_Bits = 0x01 << 26 //+ ADC Trigger 3 on Timer D compare 4.
	AD3TDPER ADC3R_Bits = 0x01 << 27 //+ ADC Trigger 3 on Timer D period.
	AD3TEC2  ADC3R_Bits = 0x01 << 28 //+ ADC Trigger 3 on Timer E compare 2.
	AD3TEC3  ADC3R_Bits = 0x01 << 29 //+ ADC Trigger 3 on Timer E compare 3.
	AD3TEC4  ADC3R_Bits = 0x01 << 30 //+ ADC Trigger 3 on Timer E compare 4.
	AD3TEPER ADC3R_Bits = 0x01 << 31 //+ ADC Trigger 3 on Timer E period.
)

const (
	AD3MC1n   = 0
	AD3MC2n   = 1
	AD3MC3n   = 2
	AD3MC4n   = 3
	AD3MPERn  = 4
	AD3EEV1n  = 5
	AD3EEV2n  = 6
	AD3EEV3n  = 7
	AD3EEV4n  = 8
	AD3EEV5n  = 9
	AD3TAC2n  = 10
	AD3TAC3n  = 11
	AD3TAC4n  = 12
	AD3TAPERn = 13
	AD3TARSTn = 14
	AD3TBC2n  = 15
	AD3TBC3n  = 16
	AD3TBC4n  = 17
	AD3TBPERn = 18
	AD3TBRSTn = 19
	AD3TCC2n  = 20
	AD3TCC3n  = 21
	AD3TCC4n  = 22
	AD3TCPERn = 23
	AD3TDC2n  = 24
	AD3TDC3n  = 25
	AD3TDC4n  = 26
	AD3TDPERn = 27
	AD3TEC2n  = 28
	AD3TEC3n  = 29
	AD3TEC4n  = 30
	AD3TEPERn = 31
)

const (
	AD4MC1   ADC4R_Bits = 0x01 << 0  //+ ADC Trigger 4 on master compare 1.
	AD4MC2   ADC4R_Bits = 0x01 << 1  //+ ADC Trigger 4 on master compare 2.
	AD4MC3   ADC4R_Bits = 0x01 << 2  //+ ADC Trigger 4 on master compare 3.
	AD4MC4   ADC4R_Bits = 0x01 << 3  //+ ADC Trigger 4 on master compare 4.
	AD4MPER  ADC4R_Bits = 0x01 << 4  //+ ADC Trigger 4 on master period.
	AD4EEV6  ADC4R_Bits = 0x01 << 5  //+ ADC Trigger 4 on external event 6.
	AD4EEV7  ADC4R_Bits = 0x01 << 6  //+ ADC Trigger 4 on external event 7.
	AD4EEV8  ADC4R_Bits = 0x01 << 7  //+ ADC Trigger 4 on external event 8.
	AD4EEV9  ADC4R_Bits = 0x01 << 8  //+ ADC Trigger 4 on external event 9.
	AD4EEV10 ADC4R_Bits = 0x01 << 9  //+ ADC Trigger 4 on external event 10.
	AD4TAC2  ADC4R_Bits = 0x01 << 10 //+ ADC Trigger 4 on Timer A compare 2.
	AD4TAC3  ADC4R_Bits = 0x01 << 11 //+ ADC Trigger 4 on Timer A compare 3.
	AD4TAC4  ADC4R_Bits = 0x01 << 12 //+ ADC Trigger 4 on Timer A compare 4.
	AD4TAPER ADC4R_Bits = 0x01 << 13 //+ ADC Trigger 4 on Timer A period.
	AD4TBC2  ADC4R_Bits = 0x01 << 14 //+ ADC Trigger 4 on Timer B compare 2.
	AD4TBC3  ADC4R_Bits = 0x01 << 15 //+ ADC Trigger 4 on Timer B compare 3.
	AD4TBC4  ADC4R_Bits = 0x01 << 16 //+ ADC Trigger 4 on Timer B compare 4.
	AD4TBPER ADC4R_Bits = 0x01 << 17 //+ ADC Trigger 4 on Timer B period.
	AD4TCC2  ADC4R_Bits = 0x01 << 18 //+ ADC Trigger 4 on Timer C compare 2.
	AD4TCC3  ADC4R_Bits = 0x01 << 19 //+ ADC Trigger 4 on Timer C compare 3.
	AD4TCC4  ADC4R_Bits = 0x01 << 20 //+ ADC Trigger 4 on Timer C compare 4.
	AD4TCPER ADC4R_Bits = 0x01 << 21 //+ ADC Trigger 4 on Timer C period.
	AD4TCRST ADC4R_Bits = 0x01 << 22 //+ ADC Trigger 4 on Timer C reset.
	AD4TDC2  ADC4R_Bits = 0x01 << 23 //+ ADC Trigger 4 on Timer D compare 2.
	AD4TDC3  ADC4R_Bits = 0x01 << 24 //+ ADC Trigger 4 on Timer D compare 3.
	AD4TDC4  ADC4R_Bits = 0x01 << 25 //+ ADC Trigger 4 on Timer D compare 4.
	AD4TDPER ADC4R_Bits = 0x01 << 26 //+ ADC Trigger 4 on Timer D period.
	AD4TDRST ADC4R_Bits = 0x01 << 27 //+ ADC Trigger 4 on Timer D reset.
	AD4TEC2  ADC4R_Bits = 0x01 << 28 //+ ADC Trigger 4 on Timer E compare 2.
	AD4TEC3  ADC4R_Bits = 0x01 << 29 //+ ADC Trigger 4 on Timer E compare 3.
	AD4TEC4  ADC4R_Bits = 0x01 << 30 //+ ADC Trigger 4 on Timer E compare 4.
	AD4TERST ADC4R_Bits = 0x01 << 31 //+ ADC Trigger 4 on Timer E reset.
)

const (
	AD4MC1n   = 0
	AD4MC2n   = 1
	AD4MC3n   = 2
	AD4MC4n   = 3
	AD4MPERn  = 4
	AD4EEV6n  = 5
	AD4EEV7n  = 6
	AD4EEV8n  = 7
	AD4EEV9n  = 8
	AD4EEV10n = 9
	AD4TAC2n  = 10
	AD4TAC3n  = 11
	AD4TAC4n  = 12
	AD4TAPERn = 13
	AD4TBC2n  = 14
	AD4TBC3n  = 15
	AD4TBC4n  = 16
	AD4TBPERn = 17
	AD4TCC2n  = 18
	AD4TCC3n  = 19
	AD4TCC4n  = 20
	AD4TCPERn = 21
	AD4TCRSTn = 22
	AD4TDC2n  = 23
	AD4TDC3n  = 24
	AD4TDC4n  = 25
	AD4TDPERn = 26
	AD4TDRSTn = 27
	AD4TEC2n  = 28
	AD4TEC3n  = 29
	AD4TEC4n  = 30
	AD4TERSTn = 31
)

const (
	CAL      DLLCR_Bits = 0x01 << 0 //+ DLL calibration start.
	CALEN    DLLCR_Bits = 0x01 << 1 //+ DLL calibration enable.
	CALRTE   DLLCR_Bits = 0x03 << 2 //+ DLL calibration rate.
	CALRTE_0 DLLCR_Bits = 0x01 << 2 //  DLL calibration rate bit 0.
	CALRTE_1 DLLCR_Bits = 0x02 << 2 //  DLL calibration rate bit 1.
)

const (
	CALn    = 0
	CALENn  = 1
	CALRTEn = 2
)
