// +build f303xe

// Peripheral: HRTIM_Timerx_Periph  High resolution Timer (HRTIM).
// Instances:
// Registers:
//  0x00 32  TIMxCR   HRTIM Timerx control register.
//  0x04 32  TIMxISR  HRTIM Timerx interrupt status register.
//  0x08 32  TIMxICR  HRTIM Timerx interrupt clear register.
//  0x0C 32  TIMxDIER HRTIM Timerx DMA/interrupt enable register.
//  0x10 32  CNTxR    HRTIM Timerx counter register.
//  0x14 32  PERxR    HRTIM Timerx period register.
//  0x18 32  REPxR    HRTIM Timerx repetition register.
//  0x1C 32  CMP1xR   HRTIM Timerx compare 1 register.
//  0x20 32  CMP1CxR  HRTIM Timerx compare 1 compound register.
//  0x24 32  CMP2xR   HRTIM Timerx compare 2 register.
//  0x28 32  CMP3xR   HRTIM Timerx compare 3 register.
//  0x2C 32  CMP4xR   HRTIM Timerx compare 4 register.
//  0x30 32  CPT1xR   HRTIM Timerx capture 1 register.
//  0x34 32  CPT2xR   HRTIM Timerx capture 2 register.
//  0x38 32  DTxR     HRTIM Timerx dead time register.
//  0x3C 32  SETx1R   HRTIM Timerx output 1 set register.
//  0x40 32  RSTx1R   HRTIM Timerx output 1 reset register.
//  0x44 32  SETx2R   HRTIM Timerx output 2 set register.
//  0x48 32  RSTx2R   HRTIM Timerx output 2 reset register.
//  0x4C 32  EEFxR1   HRTIM Timerx external event filtering 1 register.
//  0x50 32  EEFxR2   HRTIM Timerx external event filtering 2 register.
//  0x54 32  RSTxR    HRTIM Timerx Reset register.
//  0x58 32  CHPxR    HRTIM Timerx Chopper register.
//  0x5C 32  CPT1xCR  HRTIM Timerx Capture 1 register.
//  0x60 32  CPT2xCR  HRTIM Timerx Capture 2 register.
//  0x64 32  OUTxR    HRTIM Timerx Output register.
//  0x68 32  FLTxR    HRTIM Timerx Fault register.
// Import:
//  stm32/o/f303xe/mmap
package hrtim

// DO NOT EDIT THIS FILE. GENERATED BY stm32xgen.
