package scb

// DO NOT EDIT THIS FILE. GENERATED BY xgen.

import (
	"mmio"
	"unsafe"
)


func cpacr(n uint) *mmio.U32 {
	return &(*[1]mmio.U32)(unsafe.Pointer(uintptr(0xe000ed88)))[n]
}


type CPACR_Bits uint32

func (m CPACR_Bits) Load() uint32   { return cpacr(0).Bits(uint32(m)) }
func (m CPACR_Bits) Store(b uint32) { cpacr(0).StoreBits(uint32(m), b) }
func (m CPACR_Bits) Set()           { cpacr(0).SetBits(uint32(m)) }
func (m CPACR_Bits) Clear()         { cpacr(0).ClearBits(uint32(m)) }

type CPACR_Field uint16

func (f CPACR_Field) Load() int   { return cpacr(0).Field(uint16(f)) }
func (f CPACR_Field) Store(v int) { cpacr(0).SetField(uint16(f), v) }

func CPACR_Load() CPACR_Bits   { return CPACR_Bits(cpacr(0).Load()) }
func CPACR_Store(b CPACR_Bits) { cpacr(0).Store(uint32(b)) }

